### ISSUE TITLE
diy7 -eprocs <n> does not work

### ISSUE THREAD

**Issue by fshaked** [herd/herdtools7#17]
The following config produces only tests with 4 threads:
-arch AArch64
-safe Pod**,Rfe,Fre,Wse
-hexa true
-size 8
-eprocs 3
-num false

**Comment by maranget** [comment]
The problem originates in diy not checking that its list of arguments is empty. As -hexa and -eprocs are options that take no argument (they are switches), their "arguments" are parsed as ordinary command line arguments. As those are silently ignored, nothing happens.

Finally, you get test with 4 threads, because the default of option -ncprocs <n> is 4.

The fix consists in reporting diy command line arguments as errors.
