### ISSUE TITLE
Soundness issue with an AArch64 litmus test

### ISSUE THREAD

**Issue by michaliskok** [herd/herdtools7#20]
Hello,

I have the following variation of message passing, where the first read of the second thread is performed `N` times (see [attached](https://github.com/herd/herdtools7/files/3503243/mp-original.txt)).

While I would expect it to have `N + 1` executions, herd only reports 3, for different values of `N`. Is this a bug or there is something wrong with the test case?

Thank you,
Michalis

**Comment by maranget** [comment]
This is a herd bug. Thanks a lot for reporting it. The bug is now corrected in the master branch,development version, version 7.54+02(dev).

 Notice that the bug went unnoticed because most of our tests, if not all of them, use the CBZ or CBNZ instruction in place of the CMP / BC sequence.

Thanks again,

--Luc
