### ISSUE TITLE
aarch64-v07 is stronger than aarch64-v06

### ISSUE THREAD

**Issue by marcan** [herd/herdtools7#418]
#331 claimed the change from v6 to v7 is a relaxation of the model. However, this test fails with v6 and passes with v7 (tested on herd7 web):

```
AArch64 lse-atomic-al-ops-are-not-fully-ordered
""
{
0:X1=x; 0:X3=y;
1:X1=x; 1:X3=y;
}
  P0                   | P1                  ;
  MOV X0, #1           | MOV X0, #1          ;
  LDSETAL X0, X2, [X1] | LDSETAL X0, X2, [X3];
  LDR X4, [X3]         | LDR X4, [X1]        ;
exists (0:X4=0 /\ 1:X4=0)
```

Either something was made stronger in v7, or there's a bug somewhere. @jalglave

**Comment by maranget** [comment]
Hi, @marcan. The change in behavior results from a stronger `bob` relation. The changes regards the action of acquire-release AMO operations. In v6 acquire-release AMO's behave exactly as strong fences:
```
let bob =
  po; [dmb.full]; po
| po; ([A];amo;[L]); po
...
```
While in in v7, the fence effect" also operates on the (release) store of the the AMO:
```
let bob =
  po; [dmb.full]; po
| [range([A];amo;[L])]; po 
 ...
```
@jalglave would probably confirm that the change is intentional. You are right to notice that the V7 model is not a relaxation of the V6 model, strictly speaking. However, consider that, as far as I remember, the main change from V6 to V7 is a relaxation of the dependencies relations.

**Comment by marcan** [comment]
Will mentioned in another email thread that the model spec was strengthened to make that litmus test pass, so if that is what ended up in v7, that's reasonable. I was just confused that this was not mentioned in the description, and it only spoke of relaxation.

**Comment by maranget** [comment]
As far as I could figure out, the strengthening change on atomics has in fact been performed _before_ PR #331, in PR #322. The change was first performed on the default model `aarch64.cat`. In the end, PR #331 comment does not account for this change which has not been applied to the web interface model immediately. In other words some intermediate version between v6 and v7 is absent. I do not think adding it now would be very useful. Thank you for having taken the time to report the problem.

**Comment by marcan** [comment]
Ah, #322 is what I'd missed. Thanks for confirming it was just a versioning issue and the change is deliberate!
