### ISSUE TITLE
herd7 on a litmus test with a loop never terminates (expected?)

### ISSUE THREAD

**Issue by OlivierNicole** [herd/herdtools7#704]
We (@fabbing and I) ran `herd7` with the following test, but it never returns:

```
herd7 -c11 -cat rc11.cat Z.litmus -show prop -gv -o ./out
```

```c
C Z

{}

P0 (atomic_int* x) {
  int r0 = atomic_load_explicit(x,memory_order_relaxed);
  int r1 = atomic_load_explicit(x,memory_order_relaxed);
}

P1 (atomic_int* x, int* y) {
  *y = atomic_load_explicit(x, memory_order_relaxed);
  while(atomic_compare_exchange_strong(x, y, *y) == 0)
  {
    (void)42;
  }
  atomic_store_explicit(x,1,memory_order_relaxed);
}

P2 (atomic_int* x, int* a) {
  *a = atomic_load_explicit(x, memory_order_relaxed);
  while(atomic_compare_exchange_strong(x, a, *a) == 0)
  {
    (void)42;
  }
  atomic_store_explicit(x,2,memory_order_relaxed);
}

exists (0:r0=2 /\ 0:r1=0)
```

Given that I don’t know how herd works, I don’t know if this is expected or not.

Regarding why we are testing this, see https://github.com/ocaml/ocaml/pull/12681. We were blocked by the fact that the C-like language does not allow taking the address of the variable with `&`, hopefully adding an extra pointer parameter to the process is a correct way work around this limitation.

**Comment by maranget** [comment]
Hi @OlivierNicole and @fabbing, when herd7 does not return after a decent time, your first try may be to lower the loop unrolling limit., especially as your test has two loops. However, trying the minimum value `-unroll 0` does not return quickly either.  In fact it returns after a bit more than 200 seconds on my machine:
```
% safe herd7 -c11 -cat rc11.cat -unroll 0 Z.litmus 
Test Z Allowed
States 7
0:r0=0; 0:r1=0;
0:r0=0; 0:r1=1;
0:r0=0; 0:r1=2;
0:r0=1; 0:r1=1;
0:r0=1; 0:r1=2;
0:r0=2; 0:r1=1;
0:r0=2; 0:r1=2;
Loop No
Witnesses
Positive: 0 Negative: 150
Condition exists (0:r0=2 /\ 0:r1=0)
Observation Z Never 0 150
Time Z 245.70
Hash=41819447419db225f13d8cf0508c7ad4
```

So the next step is to discard execution candidates that violate the 'sc-per-location` condition (which is  possible because the rc11.cat model is stronger than sc-per-location). Herd manual excerpt:

> **-optace <true|iico|false>** Optimise the axiomatic candidate execution stage. When enabled by -optace true, herd7 does not generate candidate executions that fail the uniproc test. The default is “true” for internal models (except the minimal model), and “false” for text file models. Notice that -model uniproc.cat and -model minimal.cat -optace true should yield identical results, the second being faster. Setting -optace true can lower the execution time significantly, but one should pay attention not to design models that forget the uniproc condition.


Then, running `herd7  -c11 -cat rc11.cat -unroll 0 -optace true Z.litmus` returns in a few seconds, yielding the same result and `herd7 -c11 -cat rc11.cat -unroll 1 -optace true Z.litmus` returns in about 90 sec., still with the same result.

**Comment by OlivierNicole** [comment]
Thank you for your answer! If I understand correctly, it should suffice to get the same result with `-unroll 2` to ensure that the condition is always true (since there is only one concurrent store, the loop should not run more than twice).

**Comment by OlivierNicole** [comment]
Since this does not look like an unexpected behaviour, I am closing my issue.
